// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/julienschmidt/httprouter"
	configurationhttp "github.com/mjur/zippo/pkg/configuration/http"
	nethttp "net/http"
	"sync"
)

// Ensure, that HandlerMock does implement configurationhttp.Handler.
// If this is not the case, regenerate this file with moq.
var _ configurationhttp.Handler = &HandlerMock{}

// HandlerMock is a mock implementation of configurationhttp.Handler.
//
// 	func TestSomethingThatUsesHandler(t *testing.T) {
//
// 		// make and configure a mocked configurationhttp.Handler
// 		mockedHandler := &HandlerMock{
// 			GetMainSkuFunc: func(w nethttp.ResponseWriter, r *nethttp.Request, params httprouter.Params)  {
// 				panic("mock out the GetMainSku method")
// 			},
// 		}
//
// 		// use mockedHandler in code that requires configurationhttp.Handler
// 		// and then make assertions.
//
// 	}
type HandlerMock struct {
	// GetMainSkuFunc mocks the GetMainSku method.
	GetMainSkuFunc func(w nethttp.ResponseWriter, r *nethttp.Request, params httprouter.Params)

	// calls tracks calls to the methods.
	calls struct {
		// GetMainSku holds details about calls to the GetMainSku method.
		GetMainSku []struct {
			// W is the w argument value.
			W nethttp.ResponseWriter
			// R is the r argument value.
			R *nethttp.Request
			// Params is the params argument value.
			Params httprouter.Params
		}
	}
	lockGetMainSku sync.RWMutex
}

// GetMainSku calls GetMainSkuFunc.
func (mock *HandlerMock) GetMainSku(w nethttp.ResponseWriter, r *nethttp.Request, params httprouter.Params) {
	if mock.GetMainSkuFunc == nil {
		panic("HandlerMock.GetMainSkuFunc: method is nil but Handler.GetMainSku was just called")
	}
	callInfo := struct {
		W      nethttp.ResponseWriter
		R      *nethttp.Request
		Params httprouter.Params
	}{
		W:      w,
		R:      r,
		Params: params,
	}
	mock.lockGetMainSku.Lock()
	mock.calls.GetMainSku = append(mock.calls.GetMainSku, callInfo)
	mock.lockGetMainSku.Unlock()
	mock.GetMainSkuFunc(w, r, params)
}

// GetMainSkuCalls gets all the calls that were made to GetMainSku.
// Check the length with:
//     len(mockedHandler.GetMainSkuCalls())
func (mock *HandlerMock) GetMainSkuCalls() []struct {
	W      nethttp.ResponseWriter
	R      *nethttp.Request
	Params httprouter.Params
} {
	var calls []struct {
		W      nethttp.ResponseWriter
		R      *nethttp.Request
		Params httprouter.Params
	}
	mock.lockGetMainSku.RLock()
	calls = mock.calls.GetMainSku
	mock.lockGetMainSku.RUnlock()
	return calls
}
